/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2026-10-02-bb6ce62622"
#endif /* AVUTIL_FFVERSION_H */
